import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Screen } from '@/src/components/Screen';
import { PageHeader, SectionLabel, Surface } from '@/src/components/UI';
import { colors, radius, spacing } from '@/src/theme/tokens';

type LibraryView = 'empty' | 'loading' | 'content';

export default function LibraryScreen() {
  const [view, setView] = useState<LibraryView>('empty');
  return <Screen><PageHeader title="Library" detail="Your SAVI outputs, in one place." /><View style={styles.switcher}>{(['empty', 'loading', 'content'] as LibraryView[]).map((item) => <Pressable key={item} onPress={() => setView(item)} style={[styles.switch, view === item && styles.switchActive]}><Text style={[styles.switchText, view === item && styles.switchTextActive]}>{item}</Text></Pressable>)}</View><SectionLabel>{view === 'content' ? 'Recent output' : 'Your library'}</SectionLabel>{view === 'empty' ? <EmptyState /> : null}{view === 'loading' ? <LoadingState /> : null}{view === 'content' ? <ContentState /> : null}<Text style={styles.note}>Stage 1 structure only. Library data is not connected to SAVI yet.</Text></Screen>;
}

function EmptyState() { return <Surface style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="folder-open-outline" color={colors.violet} size={28} /></View><Text style={styles.emptyTitle}>Nothing saved yet</Text><Text style={styles.emptyCopy}>Your generated images, video, audio, and files will appear here when mobile access is connected.</Text></Surface>; }
function LoadingState() { return <View style={styles.loadingList}>{[1, 2, 3].map((item) => <Surface key={item} style={styles.loadingCard}><View style={styles.shimmer} /><View style={styles.loadingCopy}><View style={styles.barWide} /><View style={styles.barShort} /></View></Surface>)}</View>; }
function ContentState() { return <View style={styles.contentList}><Surface style={styles.file}><View style={styles.preview}><Ionicons name="image-outline" color={colors.blue} size={25} /></View><View style={styles.fileCopy}><Text style={styles.fileTitle}>Concept art</Text><Text style={styles.fileMeta}>Image · just now</Text></View><Ionicons name="ellipsis-horizontal" color={colors.textMuted} size={19} /></Surface><Text style={styles.mockNotice}>Sample content state for the Stage 1 mobile shell.</Text></View>; }

const styles = StyleSheet.create({
  switcher: { alignSelf: 'flex-start', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.pill, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', marginBottom: spacing.xl, padding: 3 }, switch: { borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 7 }, switchActive: { backgroundColor: colors.surfaceStrong }, switchText: { color: colors.textSubtle, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' }, switchTextActive: { color: colors.text }, empty: { alignItems: 'center', minHeight: 265, justifyContent: 'center', paddingHorizontal: spacing.xl }, emptyIcon: { alignItems: 'center', backgroundColor: '#251D42', borderRadius: 18, height: 58, justifyContent: 'center', marginBottom: spacing.md, width: 58 }, emptyTitle: { color: colors.text, fontSize: 19, fontWeight: '800', marginBottom: spacing.xs }, emptyCopy: { color: colors.textMuted, fontSize: 13, lineHeight: 20, textAlign: 'center' }, loadingList: { gap: spacing.xs }, loadingCard: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, padding: spacing.sm }, shimmer: { backgroundColor: colors.surfaceStrong, borderRadius: 12, height: 54, width: 54 }, loadingCopy: { flex: 1, gap: 9 }, barWide: { backgroundColor: colors.surfaceStrong, borderRadius: 4, height: 11, width: '70%' }, barShort: { backgroundColor: colors.surfaceStrong, borderRadius: 4, height: 9, width: '42%' }, contentList: { gap: spacing.sm }, file: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, padding: spacing.sm }, preview: { alignItems: 'center', backgroundColor: '#18263B', borderRadius: 12, height: 54, justifyContent: 'center', width: 54 }, fileCopy: { flex: 1, gap: 4 }, fileTitle: { color: colors.text, fontSize: 15, fontWeight: '800' }, fileMeta: { color: colors.textMuted, fontSize: 12 }, mockNotice: { color: colors.textSubtle, fontSize: 12, lineHeight: 18, textAlign: 'center' }, note: { color: colors.textSubtle, fontSize: 12, lineHeight: 18, marginTop: spacing.xl, textAlign: 'center' }, });
